apiVersion: v1
kind: Service
metadata:
  name: calculation-management-service
spec:
  type: LoadBalancer # Exposes the service with an external IP
  selector:
    app: calculation-management-service
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Container port
